#!/bin/sh

# define your crates in an array
CRATE[1]=/mnt/files/racoon/xwax/library
CRATE[2]=/mnt/files/racoon/xwax/recent
CRATE[3]=/mnt/files/racoon/xwax/tmp
CRATE[4]=/mnt/files/racoon/xwax/re-edits
CRATE[5]=/mnt/files/racoon/xwax/dubstep
CRATE[6]=/mnt/files/racoon/xwax/hip_hop
CRATE[7]=/mnt/files/racoon/xwax/funk_and_soul

# define import and scan scripts
IMPORT=/home/racoon/bin/xwax-import-twitter
SCAN=/home/racoon/bin/xwax-scan

# define last_played file
LASTP=/tmp/xwax_last_played.txt

# create a string for use in the commandline
CRATESTRING=""
for item in ${CRATE[*]}
do
    CRATESTRING="$CRATESTRING-l $item "
done

# delete last_played file at startup
if [ -f "$LASTP" ]; then rm $LASTP; fi

# alsa native instruments audio4dj
/usr/bin/xwax -i $IMPORT -s $SCAN $CRATESTRING -m 2 -a plughw:Audio4DJ,0,0 -a plughw:Audio4DJ,0,1

# alsa serato sl2
#/usr/bin/xwax -i $IMPORT -s $SCAN $CRATESTRING -m 2 -a plughw:2,0 -a plughw:2,1 -p

# jack setup
#/usr/bin/xwax -i $IMPORT -s $SCAN $CRATESTRING -m 2 -j deck0 -j deck1
